//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyFileVersion("0.0.705.1540")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyInformationalVersion("0.0.705.1540-debug")]

// Generated by the MSBuild WriteCodeFragment class on 7/5/2015 3:40:15 PM.

